---
language: python
services: docker

env:
  global:
    - ROLE_NAME=ansible-role-users
  matrix:
    - MOLECULE_DISTRO=centos7

install:
  - pip install molecule docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
