---
# tasks file for ansible-role-users
- name: Create groups from list
  group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ groups_items }}"
  when: groups_items is defined

- name: Create users from list
  user:
    name: "{{ item.user }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: "{{ item.state | default('present') }}"
    groups: "{{ item.groups | default('') }}"
    password: "{{ item.password|default(omit) }}"
    update_password: always
  loop: "{{ users_items }}"
  when: item.state == "present"

- name: Creating a list of users
  shell: cat /etc/passwd | cut -f1 -d":"
  register: sshkeys_users
  changed_when: false

- include: key.yml
  loop: "{{ users_items }}"
  when: item.key is defined and item.key

- name: Change /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.user }} ALL=.*'
    line: '{{ item.user }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    backup: true
  loop: "{{ users_items }}"
  when: (item.sudo_without_password is defined and item.sudo_without_password) and (item.sudo is defined and item.sudo)
  notify:
    - Verifying sshd configurations
    - Reload sshd configurations

- name: Add user to group wheel
  user:
    name: "{{ item.user }}"
    groups: ['wheel']
    append: true
  loop: "{{ users_items }}"
  when: ( item.sudo_without_password is not defined or not item.sudo_without_password) and (item.sudo is defined and item.sudo)
  notify:
    - Verifying sshd configurations
    - Reload sshd configurations

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^.*PermitRootLogin yes$'
    line: 'PermitRootLogin no'
  when: disable_root_login|bool
  notify:
    - Verifying sshd configurations
    - Reload sshd configurations
