---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yaml-lint.yml .
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: "timon2013/centos-systemd-ssh"
    pull: true
    pre_build_image: true
    command: "/usr/sbin/init"
    kill_signal: "RTMIN+3"
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/run"

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: default
verifier:
  name: testinfra
